"""GitHub API client for posting comments."""
import httpx
import hmac
import hashlib
from typing import Optional
import logging

logger = logging.getLogger(__name__)


def verify_github_signature(payload: bytes, signature: str, secret: str) -> bool:
    """
    Verify GitHub webhook signature.

    Args:
        payload: Raw request body bytes
        signature: X-Hub-Signature-256 header value
        secret: Webhook secret configured in GitHub

    Returns:
        True if signature is valid, False otherwise
    """
    if not signature or not secret:
        return False

    expected = 'sha256=' + hmac.new(
        secret.encode(),
        payload,
        hashlib.sha256
    ).hexdigest()

    return hmac.compare_digest(expected, signature)


class GitHubClient:
    """Client for GitHub API operations."""

    def __init__(self, token: str):
        self.token = token
        self.base_url = "https://api.github.com"
        self.timeout = 30.0

    async def post_issue_comment(
        self,
        owner: str,
        repo: str,
        issue_number: int,
        body: str
    ) -> Optional[int]:
        """
        Post a comment on a GitHub issue.

        Args:
            owner: Repository owner (user or org)
            repo: Repository name
            issue_number: Issue number
            body: Comment body (markdown supported)

        Returns:
            Comment ID if successful, None on error
        """
        url = f"{self.base_url}/repos/{owner}/{repo}/issues/{issue_number}/comments"
        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28"
        }
        payload = {"body": body}

        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.post(url, json=payload, headers=headers)
                response.raise_for_status()

                data = response.json()
                comment_id = data.get("id")
                logger.info(f"Posted comment {comment_id} on {owner}/{repo}#{issue_number}")
                return comment_id

        except httpx.HTTPStatusError as e:
            logger.error(f"GitHub API error: {e.response.status_code} - {e.response.text}")
            return None
        except Exception as e:
            logger.error(f"Error posting GitHub comment: {e}")
            return None

    def format_ai_response(self, analysis: str) -> str:
        """
        Format AI analysis as a GitHub comment.

        Args:
            analysis: Raw AI analysis text

        Returns:
            Formatted markdown comment
        """
        return f"""🤖 **AI Analysis**

{analysis}

---
*Generated by Open WebUI AI Assistant*"""
