"""GitHub API client for posting comments."""
import httpx
import hmac
import hashlib
from typing import Optional
import logging

logger = logging.getLogger(__name__)


def verify_github_signature(payload: bytes, signature: str, secret: str) -> bool:
    """
    Verify GitHub webhook signature.

    Args:
        payload: Raw request body bytes
        signature: X-Hub-Signature-256 header value
        secret: Webhook secret configured in GitHub

    Returns:
        True if signature is valid, False otherwise
    """
    if not signature or not secret:
        return False

    expected = 'sha256=' + hmac.new(
        secret.encode(),
        payload,
        hashlib.sha256
    ).hexdigest()

    return hmac.compare_digest(expected, signature)


class GitHubClient:
    """Client for GitHub API operations."""

    def __init__(self, token: str):
        self.token = token
        self.base_url = "https://api.github.com"
        self.timeout = 30.0

    async def post_issue_comment(
        self,
        owner: str,
        repo: str,
        issue_number: int,
        body: str
    ) -> Optional[int]:
        """
        Post a comment on a GitHub issue.

        Args:
            owner: Repository owner (user or org)
            repo: Repository name
            issue_number: Issue number
            body: Comment body (markdown supported)

        Returns:
            Comment ID if successful, None on error
        """
        url = f"{self.base_url}/repos/{owner}/{repo}/issues/{issue_number}/comments"
        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28"
        }
        payload = {"body": body}

        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.post(url, json=payload, headers=headers)
                response.raise_for_status()

                data = response.json()
                comment_id = data.get("id")
                logger.info(f"Posted comment {comment_id} on {owner}/{repo}#{issue_number}")
                return comment_id

        except httpx.HTTPStatusError as e:
            logger.error(f"GitHub API error: {e.response.status_code} - {e.response.text}")
            return None
        except Exception as e:
            logger.error(f"Error posting GitHub comment: {e}")
            return None

    def format_ai_response(self, analysis: str) -> str:
        """
        Format AI analysis as a GitHub comment.

        Args:
            analysis: Raw AI analysis text

        Returns:
            Formatted markdown comment
        """
        return f"""🤖 **AI Analysis**

{analysis}

---
*Generated by Open WebUI AI Assistant*"""

    async def get_pr_files(
        self,
        owner: str,
        repo: str,
        pr_number: int
    ) -> Optional[str]:
        """
        Get a summary of files changed in a PR.

        Args:
            owner: Repository owner
            repo: Repository name
            pr_number: Pull request number

        Returns:
            Summary string of changed files, or None on error
        """
        url = f"{self.base_url}/repos/{owner}/{repo}/pulls/{pr_number}/files"
        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28"
        }

        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.get(url, headers=headers)
                response.raise_for_status()

                files = response.json()
                summary_lines = []
                for f in files[:30]:  # Limit to 30 files
                    filename = f.get("filename", "unknown")
                    status = f.get("status", "modified")
                    additions = f.get("additions", 0)
                    deletions = f.get("deletions", 0)
                    summary_lines.append(
                        f"- {filename} ({status}: +{additions}/-{deletions})"
                    )

                return "\n".join(summary_lines) if summary_lines else "No files changed"

        except Exception as e:
            logger.error(f"Error getting PR files: {e}")
            return None

    async def get_commits_since(
        self,
        owner: str,
        repo: str,
        since: str,
        until: str = "",
        max_count: int = 50,
    ) -> list[dict]:
        """Get commits from a repo since a given ISO timestamp."""
        url = f"{self.base_url}/repos/{owner}/{repo}/commits"
        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        params = {"since": since, "per_page": min(max_count, 100)}
        if until:
            params["until"] = until

        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.get(url, headers=headers, params=params)
                response.raise_for_status()
                commits = response.json()

            return [
                {
                    "sha": c["sha"][:7],
                    "author": c.get("commit", {}).get("author", {}).get("name", "unknown"),
                    "message": c.get("commit", {}).get("message", "").split("\n")[0],
                    "date": c.get("commit", {}).get("author", {}).get("date", ""),
                }
                for c in commits[:max_count]
            ]

        except Exception as e:
            logger.error(f"Error fetching commits for {owner}/{repo}: {e}")
            return []
