"""GitHub API client for posting comments."""
import httpx
import hmac
import hashlib
from typing import Optional
import logging

logger = logging.getLogger(__name__)


def verify_github_signature(payload: bytes, signature: str, secret: str) -> bool:
    """
    Verify GitHub webhook signature.

    Args:
        payload: Raw request body bytes
        signature: X-Hub-Signature-256 header value
        secret: Webhook secret configured in GitHub

    Returns:
        True if signature is valid, False otherwise
    """
    if not signature or not secret:
        return False

    expected = 'sha256=' + hmac.new(
        secret.encode(),
        payload,
        hashlib.sha256
    ).hexdigest()

    return hmac.compare_digest(expected, signature)


class GitHubClient:
    """Client for GitHub API operations."""

    def __init__(self, token: str):
        self.token = token
        self.base_url = "https://api.github.com"
        self.timeout = 30.0

    async def post_issue_comment(
        self,
        owner: str,
        repo: str,
        issue_number: int,
        body: str
    ) -> Optional[int]:
        """
        Post a comment on a GitHub issue.

        Args:
            owner: Repository owner (user or org)
            repo: Repository name
            issue_number: Issue number
            body: Comment body (markdown supported)

        Returns:
            Comment ID if successful, None on error
        """
        url = f"{self.base_url}/repos/{owner}/{repo}/issues/{issue_number}/comments"
        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28"
        }
        payload = {"body": body}

        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.post(url, json=payload, headers=headers)
                response.raise_for_status()

                data = response.json()
                comment_id = data.get("id")
                logger.info(f"Posted comment {comment_id} on {owner}/{repo}#{issue_number}")
                return comment_id

        except httpx.HTTPStatusError as e:
            logger.error(f"GitHub API error: {e.response.status_code} - {e.response.text}")
            return None
        except Exception as e:
            logger.error(f"Error posting GitHub comment: {e}")
            return None

    def format_ai_response(self, analysis: str) -> str:
        """
        Format AI analysis as a GitHub comment.

        Args:
            analysis: Raw AI analysis text

        Returns:
            Formatted markdown comment
        """
        return f"""🤖 **AI Analysis**

{analysis}

---
*Generated by Open WebUI AI Assistant*"""

    async def get_pr_files(
        self,
        owner: str,
        repo: str,
        pr_number: int
    ) -> Optional[str]:
        """
        Get a summary of files changed in a PR.

        Args:
            owner: Repository owner
            repo: Repository name
            pr_number: Pull request number

        Returns:
            Summary string of changed files, or None on error
        """
        url = f"{self.base_url}/repos/{owner}/{repo}/pulls/{pr_number}/files"
        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28"
        }

        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.get(url, headers=headers)
                response.raise_for_status()

                files = response.json()
                summary_lines = []
                for f in files[:30]:  # Limit to 30 files
                    filename = f.get("filename", "unknown")
                    status = f.get("status", "modified")
                    additions = f.get("additions", 0)
                    deletions = f.get("deletions", 0)
                    summary_lines.append(
                        f"- {filename} ({status}: +{additions}/-{deletions})"
                    )

                return "\n".join(summary_lines) if summary_lines else "No files changed"

        except Exception as e:
            logger.error(f"Error getting PR files: {e}")
            return None

    async def get_pr_details(
        self,
        owner: str,
        repo: str,
        pr_number: int,
    ) -> Optional[dict]:
        """Fetch full PR details including title, body, and files changed."""
        url = f"{self.base_url}/repos/{owner}/{repo}/pulls/{pr_number}"
        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                resp = await client.get(url, headers=headers)
                resp.raise_for_status()
                pr = resp.json()

                files_resp = await client.get(f"{url}/files", headers=headers)
                files_resp.raise_for_status()
                files = files_resp.json()

                return {
                    "number": pr["number"],
                    "title": pr["title"],
                    "body": pr.get("body", "") or "",
                    "author": pr["user"]["login"],
                    "branch": pr["head"]["ref"],
                    "base": pr["base"]["ref"],
                    "merged_at": pr.get("merged_at", ""),
                    "files_changed": [
                        {
                            "filename": f["filename"],
                            "status": f["status"],
                            "additions": f["additions"],
                            "deletions": f["deletions"],
                        }
                        for f in files
                    ],
                    "total_changes": sum(
                        f["additions"] + f["deletions"] for f in files
                    ),
                }
        except Exception as e:
            logger.error(f"Failed to fetch PR details: {e}")
            return None

    async def get_commits_since(
        self,
        owner: str,
        repo: str,
        since: str,
        until: str = "",
        max_count: int = 50,
    ) -> list[dict]:
        """Get commits from a repo since a given ISO timestamp."""
        url = f"{self.base_url}/repos/{owner}/{repo}/commits"
        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        params = {"since": since, "per_page": min(max_count, 100)}
        if until:
            params["until"] = until

        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.get(url, headers=headers, params=params)
                response.raise_for_status()
                commits = response.json()

            return [
                {
                    "sha": c["sha"][:7],
                    "author": c.get("commit", {}).get("author", {}).get("name", "unknown"),
                    "message": c.get("commit", {}).get("message", "").split("\n")[0],
                    "date": c.get("commit", {}).get("author", {}).get("date", ""),
                }
                for c in commits[:max_count]
            ]

        except Exception as e:
            logger.error(f"Error fetching commits for {owner}/{repo}: {e}")
            return []

    async def get_repo_overview(self, owner: str, repo: str) -> Optional[dict]:
        """Fetch repo metadata, file tree, and key file contents for analysis."""
        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                # 1. Repo metadata
                meta_resp = await client.get(
                    f"{self.base_url}/repos/{owner}/{repo}",
                    headers=headers,
                )
                meta_resp.raise_for_status()
                meta = meta_resp.json()

                # 2. File tree (top-level only via contents API)
                tree_resp = await client.get(
                    f"{self.base_url}/repos/{owner}/{repo}/contents",
                    headers=headers,
                )
                tree_resp.raise_for_status()
                tree_items = tree_resp.json()

                tree_names = [
                    f"{'d' if item.get('type') == 'dir' else 'f'} {item['name']}"
                    for item in tree_items[:50]
                ]

                # 3. Identify key files to fetch
                key_patterns = [
                    "README.md", "readme.md",
                    "docker-compose.yml", "docker-compose.yaml",
                    "docker-compose.unified.yml",
                    "package.json", "requirements.txt", "Cargo.toml",
                    "go.mod", "pyproject.toml",
                    "main.py", "app.py", "index.js", "index.ts",
                ]

                available_files = [
                    item["name"] for item in tree_items
                    if item.get("type") == "file"
                ]

                files_to_fetch = []
                for pattern in key_patterns:
                    for fname in available_files:
                        if fname.lower() == pattern.lower() and fname not in files_to_fetch:
                            files_to_fetch.append(fname)
                            break
                    if len(files_to_fetch) >= 5:
                        break

                # 4. Fetch file contents
                file_contents = {}
                for fname in files_to_fetch:
                    try:
                        file_resp = await client.get(
                            f"{self.base_url}/repos/{owner}/{repo}/contents/{fname}",
                            headers={**headers, "Accept": "application/vnd.github.raw+json"},
                        )
                        if file_resp.status_code == 200:
                            content = file_resp.text[:2000]
                            file_contents[fname] = content
                    except Exception as e:
                        logger.warning(f"Failed to fetch {fname}: {e}")

                return {
                    "owner": owner,
                    "repo": repo,
                    "full_name": f"{owner}/{repo}",
                    "description": meta.get("description", ""),
                    "language": meta.get("language", ""),
                    "topics": meta.get("topics", []),
                    "default_branch": meta.get("default_branch", "main"),
                    "stars": meta.get("stargazers_count", 0),
                    "tree": tree_names,
                    "files": file_contents,
                }

        except httpx.HTTPStatusError as e:
            logger.error(f"GitHub API error fetching repo overview: {e.response.status_code}")
            return None
        except Exception as e:
            logger.error(f"Failed to fetch repo overview: {e}")
            return None
